export { default as categoriesAnimation } from './categories'
export { default as descriptionAnimation } from './description'
export { default as imagesAnimation } from './images'
export { default as mainImageAnimation } from './mainImage'
export { default as normalViewerPortalAnimation } from './normalViewerPortal'
export { default as tagsAnimation } from './tags'